apiVersion: v2
name: postgresql
description: PostgreSQL HA via Patroni (CloudNativePG operator)
type: application
version: 1.0.0
appVersion: "16.3"
dependencies:
  - name: cloudnative-pg
    version: "0.21.5"
    repository: "https://cloudnative-pg.github.io/charts"
